### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by markf94** [R-Sweke/DeepQ-Decoding#2]
There is no license associated with this project. In order to enable other people to use your code you should consider adding one. Here's a great overview of how to do it:

https://help.github.com/articles/adding-a-license-to-a-repository/

You might want to consider a copyleft license, such as GPL-3.0, which will force any derivative work to be open sourced as well.

**Comment by R-Sweke** [comment]
Thanks - added the GPL 3.0 licence.

**Comment by markf94** [comment]
awesome!
